import test from 'node:test';
import assert from 'node:assert/strict';
import {FISH,ISLANDS,RODS} from '../shared/catalog.js';
import {newProfile,rng,makeCatch,awardCatch,sell,buy,unlock,equip,selectFish,inHours} from '../shared/rules.js';
import {newMini,stepMini} from '../shared/minigame.js';
import {tileAt,walkable,zoneAt,SPAWN,BOAT,DOCK,createProps,obstructed} from '../shared/world.js';
test('50 espécies exclusivas, com distribuição e fichas completas',()=>{
 assert.equal(FISH.length,50);assert.equal(new Set(FISH.map(f=>f.name)).size,50);assert.equal(new Set(FISH.map(f=>JSON.stringify([f.shape,f.pattern,f.anatomy]))).size,50);
 for(const i of ISLANDS){const species=FISH.filter(f=>f.island===i.id);assert.equal(species.length,10);assert.deepEqual([0,1,2,3,4].map(r=>species.filter(f=>f.rarity===r).length),[3,2,2,2,1]);assert.equal(Math.round(species.reduce((s,f)=>s+f.chance,0)),100);for(const f of species){assert.ok(f.minWeight<f.maxWeight);assert.ok(f.minSize<f.maxSize);assert.equal(f.palette.length,3);assert.ok(f.difficulty>=20&&f.difficulty<=95);assert.ok(f.value>0);}}
});
test('Captura aleatória respeita peso, coleção e recordes após venda',()=>{const p=newProfile(),f=FISH[0],random=rng(34);for(let n=0;n<20;n++){const c=makeCatch(f,random);assert.ok(c.weight>=f.minWeight&&c.weight<=f.maxWeight);awardCatch(p,c);}const best=Math.max(...p.inventory.map(c=>c.weight));assert.equal(p.collection[f.id].best,best);assert.equal(p.collection[f.id].count,20);const worth=p.inventory.reduce((s,c)=>s+c.value,0);assert.equal(sell(p,'all'),worth);assert.equal(p.coins,50+worth);assert.equal(p.inventory.length,0);assert.equal(p.collection[f.id].count,20);assert.throws(()=>sell(p,'all'));});
test('Economia impede equipamento inicial avançado, duplicatas e saldo negativo',()=>{const p=newProfile();assert.throws(()=>buy(p,'rod-5'));assert.equal(p.coins,50);p.coins=200;buy(p,'rod-1');assert.equal(p.coins,40);assert.equal(p.rod,1);assert.throws(()=>buy(p,'rod-1'));buy(p,'bait-1');assert.equal(p.baits[1],10);equip(p,'bait',0);assert.equal(p.bait,0);assert.throws(()=>equip(p,'rod',5));});
test('Cinco rotas exigem capturas, vara equipada, licença anterior e moedas',()=>{const p=newProfile();p.coins=100000;assert.throws(()=>unlock(p,1));for(const i of ISLANDS.slice(1)){p.totalCatches=i.catches;p.rod=i.rod;assert.throws(()=>unlock({...p,unlocked:[0]},4));unlock(p,i.id);assert.ok(p.unlocked.includes(i.id));const balance=p.coins;unlock(p,i.id);assert.equal(p.coins,balance);}assert.equal(p.unlocked.length,5);});
test('Seleção usa ilha, área, horário e isca',()=>{const p=newProfile(),random=rng(78);for(let island=0;island<5;island++)for(let zone=0;zone<3;zone++)for(const hour of [0,9,19])for(let n=0;n<100;n++){const f=selectFish(p,island,zone,hour,random);assert.equal(f.island,island);assert.equal(f.zone,zone);assert.ok(inHours(f,hour));}});
test('Minigame permite capturar todas as espécies e distingue falha',()=>{for(const f of FISH){const s=newMini(f.difficulty,RODS[Math.min(5,f.island+1)],123);for(let frame=0;frame<3600&&!s.finished;frame++)stepMini(s,s.bar>s.fish,1/60);assert.equal(s.progress,1,`Controle inviável: ${f.name}`);}const s=newMini(80,RODS[0],42);for(let i=0;i<3600&&!s.finished;i++)stepMini(s,false,1/60);assert.ok(s.finished);assert.ok(s.progress<1);});
test('Todos os mapas têm píer, barco, lagos, mar profundo e caminho à loja',()=>{for(const i of ISLANDS){assert.ok(walkable(i.id,SPAWN.x,SPAWN.y));assert.ok(walkable(i.id,DOCK.x,DOCK.y));assert.ok(walkable(i.id,BOAT.x,BOAT.y,true));assert.equal(zoneAt(i.id,1184,660),0);assert.equal(zoneAt(i.id,1450,660),2);assert.equal(zoneAt(i.id,640,432),1);const props=createProps(i.id);for(let x=SPAWN.x;x>=860;x-=8)assert.equal(obstructed(i.id,x,576,props),false,`Caminho ao píer bloqueado na ilha ${i.id}, x ${x}`);for(let y=576;y>=493;y-=8)assert.equal(obstructed(i.id,860,y,props),false);assert.equal(tileAt(i.id,0,0),'water');}});
